export default{
    menu: document.querySelectorAll('.menu ul li'),
    conainerTbl: document.querySelector('.contTbl'),
    tblTitle: document.querySelector('.titleTbl'),
    tbl: document.querySelectorAll('.tbl'),
    tblEquipamentos: document.querySelector('[data-id="equipamentos"]'),
    tblEstoque: document.querySelector('[data-id="estoque"]'),
    tblEntradas: document.querySelector('[data-id="entrada"]'),
    tblSaidas: document.querySelector('[data-id="saida"]'),
    tblSenhas: document.querySelector('[data-id="senhas"]'),
    tblDownloads: document.querySelector('[data-id="downloads"]'),
    tblTelefone: document.querySelector('[data-id="telefones"]'),
    subMenu: document.querySelector('.SubMenu'),
    subMenuItem: document.querySelectorAll('.submenu-item'),
    imgBackground: document.querySelector('.imgBack'),
    btnAdd: document.querySelector('.fa-circle-plus'),
    backmodal: document.querySelector('.backmodal'),
    loading: document.querySelector('.loading'),
    modal: document.querySelector('.modal'),
    formu: document.querySelectorAll('.formulario'),
    formEquipamentos: document.querySelector('#formEquipamentos'),
    formDownloads: document.querySelector('#formDownloads'),
    formTelefones: document.querySelector('#formTelefones'),
    formSenhas: document.querySelector('#formSenhas'),
    formEntrada: document.querySelector('#formEntrada'),
    formSaida: document.querySelector('#formSaida'),
    inputForm: document.querySelectorAll('.formulario input, .formulario select, .formulario textarea'),
    inputID: document.querySelectorAll('.formulario [name="Id"]'),
    divEquipamento: document.querySelectorAll('.formulario .spaceInput'),
    iconeEquipamento: document.querySelectorAll('.eicon'),
    btnSalva: document.querySelectorAll('.save'),
    btnCancelar: document.querySelectorAll('.cancel'),
    titlemodal: document.querySelector('.titleModal'),
    formDelete: document.querySelector('.formDelete'),
    Delete: document.querySelector('.delete'),
    titleDelete: document.querySelector('.titleDelete'),
    btnConfirma: document.querySelector('.confirma'),
    email: document.querySelector('#l1'),
    password: document.querySelector('#l2'),
}


